### ISSUE TITLE
incompatible with ChatControl(+)

### ISSUE THREAD

**Issue by R4zzer** [MultiChat/Documentation#5]
Hey, the plugin ChatControl is very useful for stop spamming, insults and more.
Can you make MultiChat compatible with it?

ChatControl (Free): https://www.spigotmc.org/resources/chatcontrol.271/
ChatControl+ (Paid): https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro-format-and-filter-your-chat-halloween-sale.10258/update?update=165141

Owner of ChatControl (on Spigot):
https://www.spigotmc.org/members/kangarko.3321/

**Comment by OllieMartin** [comment]
Hi there,

Sorry for the slow response, as stated on our spigot page I have had little to no free time to dedicate to the plugin.

Unfortunately bukkit plugins like this are simply not compatible with (any?) bungeecord plugins that manage chat. It would only be possible to support plugins like this by adding individual blocks of code to support every plugin separately. As such, in future versions I will definitely be adding anti spam features etc.

If I find any way in which I can easily support plugins like this in the mean time I will of course do it, otherwise I will try and code my own solution to controlling the chat in the updates to come :)

**Comment by OllieMartin** [comment]
ChatControlPlus is basically its own chat management plugin now. It covers a lot of the same features as multichat and they cannot really function together I dont think.

MultiChat 1.6 which is about to be released has some Regex chat control features, as well as a basic anti spam etc. Hopefully this will make up for the lack of compatibility. I am also going to be investigating ways in future versions to make the plugin more compatible with spigot chat editing plugins.
