### ISSUE TITLE
Error Bungee

### ISSUE THREAD

**Issue by THEJean-Kevin** [MultiChat/Documentation#7]
Version multichat : 1.5
Error log : https://pastebin.com/9eK64rDy

server link to bungee : sponge 1.10, thermos 1.7.10, spigot 1.10.2

I get this error every time I'm connect to server or I send message

**Comment by OllieMartin** [comment]
Hi there,

Unfortunately this is a limitation with older versions of bungeecord. The issue was plaguing servers running 1.7 and earlier for a long time, but md5 made an update to bungeecord to fix it in newer versions. If updating bungeecord is a viable option for you (But I’m not sure the newer versions support 1.7) then that will fix the issue immediately. Otherwise you will have to find some way to reduce your display name below that accepted limit in older versions (16 chars).

This is the commit where the issue was fixed :) https://github.com/SpigotMC/BungeeCord/commit/8b327708ee32276ed0b74527d899903a19300f3e

**Comment by THEJean-Kevin** [comment]
But actually I have chatcontrol on my 1.7 server and I have any error with this. The probleme is you set name with prefix.

**Comment by OllieMartin** [comment]
I don’t think I quite understand? You don’t want your displayname to include prefixes? My impression is that it is the entire point of a display name, it’s the name that is displayed when you chat etc. MultiChat updates the display name to include all the formatting associated with your player so it can be used by other plugins. It is only an issue on very old versions of bungeecord. Potentially I could look into having an option to not set the display name from the plugin, but this is not a feature anyone has requested until maybe now.

I shall see what I can do if this is indeed your issue :)

**Comment by THEJean-Kevin** [comment]
For example in chatcontrol when you send message, the prefix, suffix and name was added every time in every message.

You when player connect, you set the prefix and suffix with name 
bungee
`player.setDisplayName(playerdisplayname.replaceAll("&(?=[a-f,0-9,k-o,r])", "§")); `

spigot
```
Bukkit.getPlayer(playername).setDisplayName((chat.getPlayerPrefix(Bukkit.getPlayer(playername)) + nickname + chat.getPlayerSuffix(Bukkit.getPlayer(playername))).replaceAll("&(?=[a-f,0-9,k-o,r])", "§"));
			Bukkit.getPlayer(playername).setPlayerListName((chat.getPlayerPrefix(Bukkit.getPlayer(playername)) + nickname + chat.getPlayerSuffix(Bukkit.getPlayer(playername))).replaceAll("&(?=[a-f,0-9,k-o,r])", "§"));
```


So prefix+name+suffix is necessarily longer than 16 and cause this error.

**Comment by OllieMartin** [comment]
MultiChat 1.6 is about to be released and will fix this issue. Please let it regenerate your config file :)

There will be options not only to choose if MultiChat sets the display name, but you can also choose what format it sets the display name as if you ever wanted to.
